### Linear Regression Model - With Equation

In [17]:
# Equation => w = (X^T X)^-1 X^T y

import numpy as np
class LinearRegression:
    def __init__(self):
        self.w = None

    def fit(self, X, y):
        X = np.array(X)
        y = np.array(y).reshape((-1, 1))
        
        X2 = np.hstack([np.ones((X.shape[0], 1)), X])
        print("After adding bias, X is:")
        print(X2)
        
        # For Σ(x_i x_i^T)
        sum_matrix = np.zeros((X2.shape[1], X2.shape[1]))  
        for x in X2:
            # print("\n",np.outer(x,x))
            sum_matrix += np.outer(x, x)  
        
        # For X^T X
        XTX = sum_matrix
        XTX_inverse = np.linalg.pinv(XTX)

        # For Σ(y_i x_i) = X^T y
        XTy = X2.T.dot(y)

        # Calculating the weights (intercept and slope)
        self.w = XTX_inverse.dot(XTy)
        print("Weights are (intercept,slope) : ", self.w.flatten())

    def predict(self, X):

        X = np.array(X)
        X_ = np.hstack([np.ones((X.shape[0], 1)), X]) 
        return X_.dot(self.w)  


X = np.array([[1,2], [2,3], [3,4], [4,5]]) 
y = np.array([3, 5, 7, 9])          

myLR = LinearRegression()
weights = myLR.fit(X, y)

predictions = myLR.predict(X)
print("Predictions:", predictions.flatten())

After adding bias, X is:
[[1. 1. 2.]
 [1. 2. 3.]
 [1. 3. 4.]
 [1. 4. 5.]]
Weights are (intercept,slope) :  [-1.84297022e-14  1.00000000e+00  1.00000000e+00]
Predictions: [3. 5. 7. 9.]
